webtalk_init -webtalk_dir /media/b1409_dewei/WorkDisk/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/synth/func/xsim/xsim.dir/cnt_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 23 20:23:21 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211528190_1777534442_210681794_763" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f8ba12b9806c59fc84c2a903fcf24e29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7cd13be20ed64105a12e548a7ea51991" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19 Tara" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3683.984 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129648_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1379335630 -regid "211528190_1777534442_210681794_763" -xml /media/b1409_dewei/WorkDisk/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/synth/func/xsim/xsim.dir/cnt_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /media/b1409_dewei/WorkDisk/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/synth/func/xsim/xsim.dir/cnt_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /media/b1409_dewei/WorkDisk/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/synth/func/xsim/xsim.dir/cnt_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
