webtalk_init -webtalk_dir /home/dewei/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/behav/xsim/xsim.dir/cnt_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan  8 15:28:57 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f7ce2cc-8fdc-40a8-ade1-86531f7b503c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7cd13be20ed64105a12e548a7ea51991" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2050.292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3323984414 -regid "" -xml /home/dewei/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/behav/xsim/xsim.dir/cnt_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dewei/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/behav/xsim/xsim.dir/cnt_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dewei/WorkSpace/zedBoard/cnt/cnt.sim/sim_1/behav/xsim/xsim.dir/cnt_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
